name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - 'feature-*'
  pull_request:
    branches:
      - master
      - 'feature-*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install lint dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only lint

    - name: Lint with Ruff
      run: poetry run ruff check .

    - name: Type check with MyPy
      run: poetry run mypy app

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only main --only test

    - name: Test with Pytest
      run: |
        poetry run pytest --cov=app --cov-report=xml

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install production dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --only main

    - name: Deploy
      run: echo "Deploying to production server..."
