name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - 'feature-*'
  pull_request:
    branches:
      - master
      - 'feature-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Lint with Ruff
      run: poetry run ruff check .

    - name: Type check with MyPy
      run: poetry run mypy app

    - name: Test with Pytest
      run: |
        poetry run pytest --cov=app --cov-report=xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Deploy
      run: echo "Deploying to production server..."
